before_script:
  - docker info

build_image:
  script:
    - docker build -t gitlab-registry.cern.ch/chweber/zx_postprocessingplotter:zx_limit_container .
    #- docker run my-docker-image /script/to/run/tests