

# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html

# I stole this GitLab CI/CD configuration file from
# https://gitlab.cern.ch/atlas-phys/exot/ueh/EXOT-2016-22/ZdZd13TeV/-/ci/editor?branch_name=master

# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

stages:          # List of stages for jobs, and their order of execution
    - code-build
    - image-build

variables:
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
    - date


code-build: # This job runs in the build stage, which runs first.
    stage: code-build
    image: atlas/athanalysis:21.2.94
    script:
        - pwd
    artifacts:
        name: rpm
        paths:
            - ZX_PostProcessingPlotter.rpm
        expire_in: 1 day


image-build:
    stage: image-build
    dependencies: [code-build]
    variables:
        FROM: atlas/athanalysis:21.2.94
        BUILD_ARG_1: CI_COMMIT_SHA=$CI_COMMIT_SHA
        BUILD_ARG_2: CI_COMMIT_REF_SLUG=$CI_COMMIT_REF_SLUG
        BUILD_ARG_3: CI_COMMIT_TAG=$CI_COMMIT_TAG
        BUILD_ARG_4: CI_JOB_URL=$CI_JOB_URL
        BUILD_ARG_5: CI_PROJECT_URL=$CI_PROJECT_URL
        TO: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    tags:
        - docker-image-build
    script:
        # script can't be empty so we need a dummy ignore command
        - ignore


